# Creating a Player Database for Players who Participated in the 2018 World Cup

the following code sets up a player database that is used in the pass iq framework

In [1]:
import numpy as np
import pandas as pd
import json
import requests

In [2]:
tournament = requests.get('https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/43.json').json()

In [3]:
match_data_url = "https://raw.githubusercontent.com/statsbomb/open-data/master/data/lineups/{}.json"

players = {}

match_ids = []
for g in tournament:
    m_id = g['match_id']
    match_ids.append(m_id)

for id in match_ids:
    all_events = requests.get(match_data_url.format(id)).json()

    for teams in all_events:
        for player in teams['lineup']:
            if player['player_id'] not in players:
                id = player['player_id']
                players[id] = {}
                players[id]['Name'] = player['player_name']
                players[id]['Games'] = {}
                players[id]['Team'] = teams['team_name']
            else:
                pass

In [4]:
print(players[5252])
df = pd.DataFrame(players).transpose()
df[df['Team'] == 'Mexico']

{'Name': 'Marwan Mohsen', 'Games': {}, 'Team': 'Egypt'}

     Games                               Name    Team
3058    {}          Javier Hernández Balcázar  Mexico
5556    {}          Miguel Arturo Layún Prado  Mexico
5560    {}        Carlos Alberto Vela Garrido  Mexico
5563    {}     José Andrés Guardado Hernández  Mexico
5564    {}      Carlos Joel Salcedo Hernández  Mexico
5567    {}       Edson Omar Álvarez Velázquez  Mexico
5571    {}      Hirving Rodrigo Lozano Bahena  Mexico
5573    {}      Héctor Alfredo Moreno Herrera  Mexico
5575    {}        Héctor Miguel Herrera López  Mexico
5576    {}  Jesús Daniel Gallardo Vasconcelos  Mexico
5577    {}   Francisco Guillermo Ochoa Magaña  Mexico
5985    {}           Jesús Manuel Corona Ruíz  Mexico
6316    {}              Oribe Peralta Morones  Mexico
6317    {}    Marco Jhonfai Fabián De La Mora  Mexico
5558    {}             Rafael Márquez Álvarez  Mexico
5561    {}                  Hugo Ayala Castro  Mexico
5568    {}      Raúl Alonso Jiménez Rodríguez  Mexico
6357    {}        Jonathan dos Santos Ramírez  Mexico
5987    {}         Giovani dos Santos Ramírez  Mexico

In [5]:
df.to_csv('player.csv')